# Generated by Django 5.0.2 on 2024-03-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_curso_entregable_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='Profesion',
            new_name='profesion',
        ),
    ]
